// <auto-generated />
namespace PetZen.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updaterequiredstatusinPet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updaterequiredstatusinPet));
        
        string IMigrationMetadata.Id
        {
            get { return "202012150148308_update required status in Pet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
